### ISSUE TITLE
Consider using github.com/jfreymuth/go-vorbis

### ISSUE THREAD

**Issue by mjibson** [xlab/libvpx-go#1]
[github.com/jfreymuth/go-vorbis](https://github.com/jfreymuth/go-vorbis) is a 100% Go ogg decoder. I've used it some and it's worked great.

**Comment by xlab** [comment]
@mjibson 
Yeah but the API doesn't match. Vorbis decoding flow is much more complex than just "fetch" and "decode", check out [a decoder](https://github.com/xlab/vorbis-go/blob/master/decoder/decoder.go)  flow I wrote on top of the native implementation. Moreover, stream in WebM does not start from "OggS" as the implementation naively expects.

http://github.com/xlab/vorbis-go has a demo application that has 100% compliance with ffmpeg, the output matches at 100%. I won't switch to github.com/jfreymuth/go-vorbis until there is any demo that works ;)

**Comment by xlab** [comment]
Pull requests are welcome though.
